/**
 * Tool execution with approval support
 */

// Registry
export { ToolsetRegistry, type ToolsetContext, type ToolsetFactory } from "./registry.js";

// Filesystem toolset
export {
  FilesystemToolset,
  createFilesystemTools,
  createReadFileTool,
  createWriteFileTool,
  createListFilesTool,
  createDeleteFileTool,
  createFileExistsTool,
  createFileInfoTool,
  type FilesystemToolResult,
  type FilesystemToolsetOptions,
  type NamedTool,
  type ZoneApprovalMap,
} from "./filesystem.js";

export {
  WorkerCallToolset,
  createCallWorkerTool,
  createNamedWorkerTool,
  checkToolNameConflict,
  type CallWorkerInput,
  type NamedWorkerInput,
  type CallWorkerResult,
  type DelegationContext,
  type WorkerCallToolsetOptions,
  type NamedWorkerToolOptions,
} from "./worker-call.js";

export {
  ShellToolset,
  createShellTool,
  createShellTools,
  executeShell,
  parseCommand,
  checkMetacharacters,
  matchShellRules,
  ShellError,
  ShellBlockedError,
  ShellConfigSchema,
  ShellRuleSchema,
  ShellDefaultSchema,
  BLOCKED_METACHARACTERS,
  MAX_OUTPUT_BYTES,
  DEFAULT_TIMEOUT,
  MAX_TIMEOUT,
  type ShellResult,
  type ShellRule,
  type ShellDefault,
  type ShellConfig,
  type ShellToolOptions,
  type ShellToolsetOptions,
  type MatchResult,
} from "./shell.js";

export {
  CustomToolset,
  createCustomToolset,
  loadCustomTools,
  wrapWithDefaultApproval,
  createToolFromFunction,
  isNamedTool,
  isZodSchema,
  extractFunctionDescription,
  CustomToolsetConfigSchema,
  type CustomToolsetConfig,
  type CustomApprovalConfig,
  type CustomToolsetOptions,
  type ToolContext,
} from "./custom.js";

// Git toolset (self-registers on import)
export {
  GitToolset,
  GitError,
  GitAuthError,
  GitTargetSchema,
  GitToolsetConfigSchema,
  CLIGitBackend,
  createCLIGitBackend,
  getGitHubAuth,
  hasGitHubAuth,
  merge,
  threeWayMerge,
  generateDiff,
  hasConflictMarkers,
  createGitTools,
  createGitStatusTool,
  createGitStageTool,
  createGitDiffTool,
  createGitPushTool,
  createGitDiscardTool,
  createGitPullTool,
  createGitMergeTool,
  createGitBranchesTool,
  type GitTarget,
  type GitHubTarget,
  type LocalTarget,
  type LocalBareTarget,
  type StagedCommit,
  type StagedFile,
  type GitStatus,
  type UnstagedFile,
  type PullResult,
  type MergeResult,
  type PushResult,
  type PushConflict,
  type BranchListResult,
  type GitToolsetConfig,
  type GitToolResult,
  type GitBackend,
  type GitToolsetOptions,
} from "./git/index.js";
